

USE DATABASE APP_PULSE;
USE SCHEMA APP_PULSE.UK;
CREATE OR ALTER view CUSTOMER_V as
select
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CONTACT_NAME,
    ADDRESS,
    CITY,
    POSTAL_CODE,
    COUNTRY
from CUSTOMER;
