
USE DATABASE APP_PULSE;
USE SCHEMA APP_PULSE.UK;
CREATE OR ALTER TABLE CUSTOMER (
CUSTOMER_ID INTEGER PRIMARY KEY,
CUSTOMER_NAME VARCHAR(50),
CONTACT_NAME VARCHAR(50),
ADDRESS VARCHAR(100),
CITY VARCHAR(50),
POSTAL_CODE VARCHAR(20),
COUNTRY VARCHAR(50)
);