

USE DATABASE APP_PULSE;
USE SCHEMA APP_PULSE.UK;
CREATE OR ALTER TABLE MERCHANT (
	MERCHANT_NO NUMBER(38,0) NOT NULL,
	NAME VARCHAR(20),
	JOB VARCHAR(20),
	MGR NUMBER(38,0),
	HIREDATE DATE,
	SAL NUMBER(10,2),
	COMM NUMBER(38,0),
	DEPTNO NUMBER(38,0),
	primary key (MERCHANT_NO)
);
