
create or replace TABLE APP_PULSE.US.EMPLOYEE (
	EMPNO NUMBER(38,0) NOT NULL,
	ENAME VARCHAR(20),
	JOB VARCHAR(20),
	MGR NUMBER(38,0),
	HIREDATE DATE,
	SAL NUMBER(10,2),
	COMM NUMBER(38,0),
	DEPTNO NUMBER(38,0),
	primary key (EMPNO)
);