
CREATE OR ALTER TABLE APP_PULSE.US.CUSTOMER (
CUSTOMER_ID INTEGER PRIMARY KEY,
CUSTOMER_NAME VARCHAR(50),
CONTACT_NAME VARCHAR(50),
ADDRESS VARCHAR(100),
CITY VARCHAR(50),
POSTAL_CODE VARCHAR(20),
COUNTRY VARCHAR(50)
);