
CREATE OR ALTER PROCEDURE APP_PULSE.US.LOAD_RAW_TO_US()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN

    -- Load CUSTOMER
    INSERT INTO APP_PULSE.US.CUSTOMER (CUST_NO, NAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT CUST_NO, NAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
    FROM APP_PULSE.RAW.CUSTOMER;

    -- Load EMPLOYEE
    INSERT INTO APP_PULSE.US.EMPLOYEE (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
    FROM APP_PULSE.RAW.EMPLOYEE;

    -- Load PUBLISHER
    INSERT INTO APP_PULSE.US.PUBLISHER (PUBLISHER_ID, NAME)
    SELECT PUBLISHER_ID, NAME
    FROM APP_PULSE.RAW.PUBLISHER;

    RETURN 'SUCCESS: Data loaded from RAW to US schema.';

EXCEPTION
    WHEN OTHER THEN
        RETURN 'ERROR: ' || SQLERRM;

END;
$$;
